// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: duplicates.sql

package sqlc

import (
	"context"
	"database/sql"
)

const dismissImageDuplicate = `-- name: DismissImageDuplicate :execrows
UPDATE image_duplicates SET status = 'dismissed', resolved_at = ? WHERE id = ? AND status = 'pending'
`

type DismissImageDuplicateParams struct {
	ResolvedAt sql.NullString
	ID         string
}

func (q *Queries) DismissImageDuplicate(ctx context.Context, arg DismissImageDuplicateParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, dismissImageDuplicate, arg.ResolvedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getImageDuplicate = `-- name: GetImageDuplicate :one
SELECT id, folder_id, image_id_a, image_id_b, distance, status, created_at, resolved_at FROM image_duplicates WHERE id = ?
`

func (q *Queries) GetImageDuplicate(ctx context.Context, id string) (ImageDuplicate, error) {
	row := q.db.QueryRowContext(ctx, getImageDuplicate, id)
	var i ImageDuplicate
	err := row.Scan(
		&i.ID,
		&i.FolderID,
		&i.ImageIDA,
		&i.ImageIDB,
		&i.Distance,
		&i.Status,
		&i.CreatedAt,
		&i.ResolvedAt,
	)
	return i, err
}

const insertImageDuplicate = `-- name: InsertImageDuplicate :exec
INSERT INTO image_duplicates (id, folder_id, image_id_a, image_id_b, distance)
VALUES (?, ?, ?, ?, ?)
ON CONFLICT (image_id_a, image_id_b) DO NOTHING
`

type InsertImageDuplicateParams struct {
	ID       string
	FolderID string
	ImageIDA string
	ImageIDB string
	Distance int64
}

func (q *Queries) InsertImageDuplicate(ctx context.Context, arg InsertImageDuplicateParams) error {
	_, err := q.db.ExecContext(ctx, insertImageDuplicate,
		arg.ID,
		arg.FolderID,
		arg.ImageIDA,
		arg.ImageIDB,
		arg.Distance,
	)
	return err
}

const listPendingDuplicates = `-- name: ListPendingDuplicates :many
SELECT d.id, d.folder_id, d.image_id_a, d.image_id_b, d.distance, d.status, d.created_at, d.resolved_at,
       a.original_filename AS a_filename,
       b.original_filename AS b_filename
FROM image_duplicates d
JOIN images a ON a.id = d.image_id_a
JOIN images b ON b.id = d.image_id_b
WHERE d.folder_id = ? AND d.status = 'pending'
ORDER BY d.created_at
`

type ListPendingDuplicatesRow struct {
	ID         string
	FolderID   string
	ImageIDA   string
	ImageIDB   string
	Distance   int64
	Status     string
	CreatedAt  string
	ResolvedAt sql.NullString
	AFilename  string
	BFilename  string
}

func (q *Queries) ListPendingDuplicates(ctx context.Context, folderID string) ([]ListPendingDuplicatesRow, error) {
	rows, err := q.db.QueryContext(ctx, listPendingDuplicates, folderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPendingDuplicatesRow
	for rows.Next() {
		var i ListPendingDuplicatesRow
		if err := rows.Scan(
			&i.ID,
			&i.FolderID,
			&i.ImageIDA,
			&i.ImageIDB,
			&i.Distance,
			&i.Status,
			&i.CreatedAt,
			&i.ResolvedAt,
			&i.AFilename,
			&i.BFilename,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolveDuplicatesForImage = `-- name: ResolveDuplicatesForImage :exec
UPDATE image_duplicates SET status = 'resolved', resolved_at = ?
WHERE (image_id_a = ? OR image_id_b = ?) AND status = 'pending'
`

type ResolveDuplicatesForImageParams struct {
	ResolvedAt sql.NullString
	ImageIDA   string
	ImageIDB   string
}

func (q *Queries) ResolveDuplicatesForImage(ctx context.Context, arg ResolveDuplicatesForImageParams) error {
	_, err := q.db.ExecContext(ctx, resolveDuplicatesForImage, arg.ResolvedAt, arg.ImageIDA, arg.ImageIDB)
	return err
}

const resolveImageDuplicate = `-- name: ResolveImageDuplicate :execrows
UPDATE image_duplicates SET status = 'resolved', resolved_at = ? WHERE id = ? AND status = 'pending'
`

type ResolveImageDuplicateParams struct {
	ResolvedAt sql.NullString
	ID         string
}

func (q *Queries) ResolveImageDuplicate(ctx context.Context, arg ResolveImageDuplicateParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, resolveImageDuplicate, arg.ResolvedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
