// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: exports.sql

package sqlc

import (
	"context"
	"database/sql"
)

const addAllFolderImagesToExport = `-- name: AddAllFolderImagesToExport :exec
INSERT INTO export_images (export_id, image_id)
SELECT ?1, id FROM images WHERE folder_id = ?2 AND is_calibration = 0
`

type AddAllFolderImagesToExportParams struct {
	ExportID string
	FolderID string
}

func (q *Queries) AddAllFolderImagesToExport(ctx context.Context, arg AddAllFolderImagesToExportParams) error {
	_, err := q.db.ExecContext(ctx, addAllFolderImagesToExport, arg.ExportID, arg.FolderID)
	return err
}

const addExportImage = `-- name: AddExportImage :exec
INSERT OR IGNORE INTO export_images (export_id, image_id) VALUES (?, ?)
`

type AddExportImageParams struct {
	ExportID string
	ImageID  string
}

func (q *Queries) AddExportImage(ctx context.Context, arg AddExportImageParams) error {
	_, err := q.db.ExecContext(ctx, addExportImage, arg.ExportID, arg.ImageID)
	return err
}

const createExport = `-- name: CreateExport :one
INSERT INTO exports (id, folder_id, user_id, expires_at) VALUES (?, ?, ?, ?) RETURNING id, folder_id, user_id, status, file_key, size_bytes, error, created_at, expires_at
`

type CreateExportParams struct {
	ID        string
	FolderID  string
	UserID    sql.NullString
	ExpiresAt string
}

func (q *Queries) CreateExport(ctx context.Context, arg CreateExportParams) (Export, error) {
	row := q.db.QueryRowContext(ctx, createExport,
		arg.ID,
		arg.FolderID,
		arg.UserID,
		arg.ExpiresAt,
	)
	var i Export
	err := row.Scan(
		&i.ID,
		&i.FolderID,
		&i.UserID,
		&i.Status,
		&i.FileKey,
		&i.SizeBytes,
		&i.Error,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const deleteExport = `-- name: DeleteExport :exec
DELETE FROM exports WHERE id = ?
`

func (q *Queries) DeleteExport(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteExport, id)
	return err
}

const getExport = `-- name: GetExport :one
SELECT id, folder_id, user_id, status, file_key, size_bytes, error, created_at, expires_at FROM exports WHERE id = ?
`

func (q *Queries) GetExport(ctx context.Context, id string) (Export, error) {
	row := q.db.QueryRowContext(ctx, getExport, id)
	var i Export
	err := row.Scan(
		&i.ID,
		&i.FolderID,
		&i.UserID,
		&i.Status,
		&i.FileKey,
		&i.SizeBytes,
		&i.Error,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const listExpiredExports = `-- name: ListExpiredExports :many
SELECT id, folder_id, user_id, status, file_key, size_bytes, error, created_at, expires_at FROM exports WHERE expires_at <= ?
`

func (q *Queries) ListExpiredExports(ctx context.Context, expiresAt string) ([]Export, error) {
	rows, err := q.db.QueryContext(ctx, listExpiredExports, expiresAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Export
	for rows.Next() {
		var i Export
		if err := rows.Scan(
			&i.ID,
			&i.FolderID,
			&i.UserID,
			&i.Status,
			&i.FileKey,
			&i.SizeBytes,
			&i.Error,
			&i.CreatedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFolderExportKeys = `-- name: ListFolderExportKeys :many
SELECT id, file_key FROM exports WHERE folder_id = ? AND file_key IS NOT NULL
`

type ListFolderExportKeysRow struct {
	ID      string
	FileKey sql.NullString
}

func (q *Queries) ListFolderExportKeys(ctx context.Context, folderID string) ([]ListFolderExportKeysRow, error) {
	rows, err := q.db.QueryContext(ctx, listFolderExportKeys, folderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFolderExportKeysRow
	for rows.Next() {
		var i ListFolderExportKeysRow
		if err := rows.Scan(&i.ID, &i.FileKey); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFolderExports = `-- name: ListFolderExports :many
SELECT id, folder_id, user_id, status, file_key, size_bytes, error, created_at, expires_at FROM exports WHERE folder_id = ? ORDER BY created_at DESC LIMIT 20
`

func (q *Queries) ListFolderExports(ctx context.Context, folderID string) ([]Export, error) {
	rows, err := q.db.QueryContext(ctx, listFolderExports, folderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Export
	for rows.Next() {
		var i Export
		if err := rows.Scan(
			&i.ID,
			&i.FolderID,
			&i.UserID,
			&i.Status,
			&i.FileKey,
			&i.SizeBytes,
			&i.Error,
			&i.CreatedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markExportFailed = `-- name: MarkExportFailed :exec
UPDATE exports SET status = 'failed', error = ? WHERE id = ?
`

type MarkExportFailedParams struct {
	Error sql.NullString
	ID    string
}

func (q *Queries) MarkExportFailed(ctx context.Context, arg MarkExportFailedParams) error {
	_, err := q.db.ExecContext(ctx, markExportFailed, arg.Error, arg.ID)
	return err
}

const markExportReady = `-- name: MarkExportReady :exec
UPDATE exports SET status = 'ready', file_key = ?, size_bytes = ?, error = NULL WHERE id = ?
`

type MarkExportReadyParams struct {
	FileKey   sql.NullString
	SizeBytes sql.NullInt64
	ID        string
}

func (q *Queries) MarkExportReady(ctx context.Context, arg MarkExportReadyParams) error {
	_, err := q.db.ExecContext(ctx, markExportReady, arg.FileKey, arg.SizeBytes, arg.ID)
	return err
}

const markExportRunning = `-- name: MarkExportRunning :exec
UPDATE exports SET status = 'running' WHERE id = ?
`

func (q *Queries) MarkExportRunning(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, markExportRunning, id)
	return err
}
