// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: filter.sql

package sqlc

import (
	"context"
	"database/sql"
)

const countImagesFiltered = `-- name: CountImagesFiltered :one
SELECT COUNT(*) FROM images i
WHERE i.folder_id = ?1
  AND i.deleted_at IS NULL
  AND (CAST(?2 AS INTEGER) IS NULL OR i.rating >= CAST(?2 AS INTEGER))
  AND (CAST(?3 AS INTEGER) IS NULL OR i.rating <= CAST(?3 AS INTEGER))
  AND (CAST(?4 AS TEXT) IS NULL OR i.uploader_nickname = CAST(?4 AS TEXT))
  AND (CAST(?5 AS TEXT) IS NULL OR datetime(i.exif_time, printf('%+d seconds', COALESCE(i.time_offset_seconds, 0))) >= CAST(?5 AS TEXT))
  AND (CAST(?6 AS TEXT) IS NULL OR datetime(i.exif_time, printf('%+d seconds', COALESCE(i.time_offset_seconds, 0))) <= CAST(?6 AS TEXT))
  AND (CAST(?7 AS INTEGER) IS NULL OR i.gps_lat IS NOT NULL)
  AND (CAST(?8 AS TEXT) IS NULL OR (
        SELECT COUNT(DISTINCT t.id) FROM image_tags it JOIN tags t ON t.id = it.tag_id
        WHERE it.image_id = i.id AND t.name IN (SELECT value FROM json_each(CAST(?8 AS TEXT)))
      ) >= ?9)
`

type CountImagesFilteredParams struct {
	FolderID   string
	RatingMin  sql.NullInt64
	RatingMax  sql.NullInt64
	Uploader   sql.NullString
	FromTime   sql.NullString
	ToTime     sql.NullString
	HasGps     sql.NullInt64
	Tags       sql.NullString
	TagsNeeded int64
}

func (q *Queries) CountImagesFiltered(ctx context.Context, arg CountImagesFilteredParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countImagesFiltered,
		arg.FolderID,
		arg.RatingMin,
		arg.RatingMax,
		arg.Uploader,
		arg.FromTime,
		arg.ToTime,
		arg.HasGps,
		arg.Tags,
		arg.TagsNeeded,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listFilteredRefs = `-- name: ListFilteredRefs :many
SELECT i.id, i.gps_lat, i.gps_lon FROM images i
WHERE i.folder_id = ?1
  AND i.deleted_at IS NULL
  AND (CAST(?2 AS INTEGER) IS NULL OR i.rating >= CAST(?2 AS INTEGER))
  AND (CAST(?3 AS INTEGER) IS NULL OR i.rating <= CAST(?3 AS INTEGER))
  AND (CAST(?4 AS TEXT) IS NULL OR i.uploader_nickname = CAST(?4 AS TEXT))
  AND (CAST(?5 AS TEXT) IS NULL OR datetime(i.exif_time, printf('%+d seconds', COALESCE(i.time_offset_seconds, 0))) >= CAST(?5 AS TEXT))
  AND (CAST(?6 AS TEXT) IS NULL OR datetime(i.exif_time, printf('%+d seconds', COALESCE(i.time_offset_seconds, 0))) <= CAST(?6 AS TEXT))
  AND (CAST(?7 AS INTEGER) IS NULL OR i.gps_lat IS NOT NULL)
  AND (CAST(?8 AS TEXT) IS NULL OR (
        SELECT COUNT(DISTINCT t.id) FROM image_tags it JOIN tags t ON t.id = it.tag_id
        WHERE it.image_id = i.id AND t.name IN (SELECT value FROM json_each(CAST(?8 AS TEXT)))
      ) >= ?9)
ORDER BY i.seq
LIMIT ?10
`

type ListFilteredRefsParams struct {
	FolderID   string
	RatingMin  sql.NullInt64
	RatingMax  sql.NullInt64
	Uploader   sql.NullString
	FromTime   sql.NullString
	ToTime     sql.NullString
	HasGps     sql.NullInt64
	Tags       sql.NullString
	TagsNeeded int64
	MaxRows    int64
}

type ListFilteredRefsRow struct {
	ID     string
	GpsLat sql.NullFloat64
	GpsLon sql.NullFloat64
}

// Ids (and positions, for the map) of every match in upload order, at most `max_rows`.
func (q *Queries) ListFilteredRefs(ctx context.Context, arg ListFilteredRefsParams) ([]ListFilteredRefsRow, error) {
	rows, err := q.db.QueryContext(ctx, listFilteredRefs,
		arg.FolderID,
		arg.RatingMin,
		arg.RatingMax,
		arg.Uploader,
		arg.FromTime,
		arg.ToTime,
		arg.HasGps,
		arg.Tags,
		arg.TagsNeeded,
		arg.MaxRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFilteredRefsRow
	for rows.Next() {
		var i ListFilteredRefsRow
		if err := rows.Scan(&i.ID, &i.GpsLat, &i.GpsLon); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFolderUploaders = `-- name: ListFolderUploaders :many
SELECT DISTINCT uploader_nickname FROM images
WHERE folder_id = ? AND deleted_at IS NULL
ORDER BY uploader_nickname
`

func (q *Queries) ListFolderUploaders(ctx context.Context, folderID string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listFolderUploaders, folderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var uploader_nickname string
		if err := rows.Scan(&uploader_nickname); err != nil {
			return nil, err
		}
		items = append(items, uploader_nickname)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listImagesFiltered = `-- name: ListImagesFiltered :many

SELECT seq, id, folder_id, original_filename, mime_type, size_bytes, width, height, sha256, uploader_nickname, rating, thumbnail_ready, preview_ready, created_at, device_key, exif_time, qr_scanned, is_calibration, calib_ref_time, time_offset_seconds, phash, phash_attempted_at, derivative_version, deleted_at, deleted_by, gps_lat, gps_lon, gps_attempted_at, sort_key, is_desc FROM (
  SELECT i.seq, i.id, i.folder_id, i.original_filename, i.mime_type, i.size_bytes, i.width, i.height, i.sha256, i.uploader_nickname, i.rating, i.thumbnail_ready, i.preview_ready, i.created_at, i.device_key, i.exif_time, i.qr_scanned, i.is_calibration, i.calib_ref_time, i.time_offset_seconds, i.phash, i.phash_attempted_at, i.derivative_version, i.deleted_at, i.deleted_by, i.gps_lat, i.gps_lon, i.gps_attempted_at, CASE CAST(?1 AS TEXT)
      WHEN 'captured' THEN COALESCE(datetime(i.exif_time, printf('%+d seconds', COALESCE(i.time_offset_seconds, 0))), '')
      WHEN 'rating' THEN printf('%03d', COALESCE(i.rating, 0))
      ELSE printf('%020d', i.seq) END AS sort_key,
         CAST(?2 AS TEXT) = 'desc' AS is_desc
  FROM images i
  WHERE i.folder_id = ?3
  AND i.deleted_at IS NULL
  AND (CAST(?4 AS INTEGER) IS NULL OR i.rating >= CAST(?4 AS INTEGER))
  AND (CAST(?5 AS INTEGER) IS NULL OR i.rating <= CAST(?5 AS INTEGER))
  AND (CAST(?6 AS TEXT) IS NULL OR i.uploader_nickname = CAST(?6 AS TEXT))
  AND (CAST(?7 AS TEXT) IS NULL OR datetime(i.exif_time, printf('%+d seconds', COALESCE(i.time_offset_seconds, 0))) >= CAST(?7 AS TEXT))
  AND (CAST(?8 AS TEXT) IS NULL OR datetime(i.exif_time, printf('%+d seconds', COALESCE(i.time_offset_seconds, 0))) <= CAST(?8 AS TEXT))
  AND (CAST(?9 AS INTEGER) IS NULL OR i.gps_lat IS NOT NULL)
  AND (CAST(?10 AS TEXT) IS NULL OR (
        SELECT COUNT(DISTINCT t.id) FROM image_tags it JOIN tags t ON t.id = it.tag_id
        WHERE it.image_id = i.id AND t.name IN (SELECT value FROM json_each(CAST(?10 AS TEXT)))
      ) >= ?11)
) AS f
WHERE CAST(?12 AS INTEGER) IS NULL
   OR (NOT f.is_desc AND (f.sort_key, f.seq) > (CAST(?13 AS TEXT), CAST(?12 AS INTEGER)))
   OR (f.is_desc AND (f.sort_key, f.seq) < (CAST(?13 AS TEXT), CAST(?12 AS INTEGER)))
ORDER BY CASE WHEN NOT f.is_desc THEN f.sort_key END ASC,
         CASE WHEN f.is_desc THEN f.sort_key END DESC,
         CASE WHEN NOT f.is_desc THEN f.seq END ASC,
         CASE WHEN f.is_desc THEN f.seq END DESC
LIMIT ?14
`

type ListImagesFilteredParams struct {
	Sort       string
	Dir        string
	FolderID   string
	RatingMin  sql.NullInt64
	RatingMax  sql.NullInt64
	Uploader   sql.NullString
	FromTime   sql.NullString
	ToTime     sql.NullString
	HasGps     sql.NullInt64
	Tags       sql.NullString
	TagsNeeded int64
	AfterSeq   sql.NullInt64
	AfterKey   sql.NullString
	PageSize   int64
}

type ListImagesFilteredRow struct {
	Seq               int64
	ID                string
	FolderID          string
	OriginalFilename  string
	MimeType          string
	SizeBytes         int64
	Width             int64
	Height            int64
	Sha256            string
	UploaderNickname  string
	Rating            sql.NullInt64
	ThumbnailReady    int64
	PreviewReady      int64
	CreatedAt         string
	DeviceKey         sql.NullString
	ExifTime          sql.NullString
	QrScanned         int64
	IsCalibration     int64
	CalibRefTime      sql.NullString
	TimeOffsetSeconds sql.NullInt64
	Phash             sql.NullInt64
	PhashAttemptedAt  sql.NullString
	DerivativeVersion int64
	DeletedAt         sql.NullString
	DeletedBy         sql.NullString
	GpsLat            sql.NullFloat64
	GpsLon            sql.NullFloat64
	GpsAttemptedAt    sql.NullString
	SortKey           interface{}
	IsDesc            bool
}

// The gallery filter. Every filter is an optional argument (NULL = not set);
// internal/filter maps a parsed query string onto these parameters.
//
//	tags         JSON array of tag names; an image needs `tags_needed` of them
//	             (all of them for "all", 1 for "any").
//	from_time / to_time
//	             bounds on the corrected capture time, "YYYY-MM-DD HH:MM:SS".
//	sort         'uploaded' | 'captured' | 'rating'; dir 'asc' | 'desc'.
//	after_key / after_seq
//	             keyset cursor: the sort_key and seq of the last row of the
//	             previous page (both NULL for the first page).
//
// The three queries below share one predicate; keep them identical.
func (q *Queries) ListImagesFiltered(ctx context.Context, arg ListImagesFilteredParams) ([]ListImagesFilteredRow, error) {
	rows, err := q.db.QueryContext(ctx, listImagesFiltered,
		arg.Sort,
		arg.Dir,
		arg.FolderID,
		arg.RatingMin,
		arg.RatingMax,
		arg.Uploader,
		arg.FromTime,
		arg.ToTime,
		arg.HasGps,
		arg.Tags,
		arg.TagsNeeded,
		arg.AfterSeq,
		arg.AfterKey,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListImagesFilteredRow
	for rows.Next() {
		var i ListImagesFilteredRow
		if err := rows.Scan(
			&i.Seq,
			&i.ID,
			&i.FolderID,
			&i.OriginalFilename,
			&i.MimeType,
			&i.SizeBytes,
			&i.Width,
			&i.Height,
			&i.Sha256,
			&i.UploaderNickname,
			&i.Rating,
			&i.ThumbnailReady,
			&i.PreviewReady,
			&i.CreatedAt,
			&i.DeviceKey,
			&i.ExifTime,
			&i.QrScanned,
			&i.IsCalibration,
			&i.CalibRefTime,
			&i.TimeOffsetSeconds,
			&i.Phash,
			&i.PhashAttemptedAt,
			&i.DerivativeVersion,
			&i.DeletedAt,
			&i.DeletedBy,
			&i.GpsLat,
			&i.GpsLon,
			&i.GpsAttemptedAt,
			&i.SortKey,
			&i.IsDesc,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listImagesMissingGPS = `-- name: ListImagesMissingGPS :many
SELECT i.id FROM images i
JOIN folders f ON f.id = i.folder_id
WHERE i.gps_attempted_at IS NULL AND f.deleted_at IS NULL
  AND NOT EXISTS (
    SELECT 1 FROM jobs j
    WHERE j.type = 'extract_gps' AND j.status IN ('pending', 'running')
      AND json_extract(j.payload, '$.image_id') = i.id
  )
`

// Trashed images are included: they may be restored.
func (q *Queries) ListImagesMissingGPS(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listImagesMissingGPS)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markGPSAttempted = `-- name: MarkGPSAttempted :exec
UPDATE images SET gps_attempted_at = ? WHERE id = ?
`

type MarkGPSAttemptedParams struct {
	GpsAttemptedAt sql.NullString
	ID             string
}

func (q *Queries) MarkGPSAttempted(ctx context.Context, arg MarkGPSAttemptedParams) error {
	_, err := q.db.ExecContext(ctx, markGPSAttempted, arg.GpsAttemptedAt, arg.ID)
	return err
}

const setImageGPS = `-- name: SetImageGPS :exec
UPDATE images SET gps_lat = ?, gps_lon = ?, gps_attempted_at = ? WHERE id = ?
`

type SetImageGPSParams struct {
	GpsLat         sql.NullFloat64
	GpsLon         sql.NullFloat64
	GpsAttemptedAt sql.NullString
	ID             string
}

func (q *Queries) SetImageGPS(ctx context.Context, arg SetImageGPSParams) error {
	_, err := q.db.ExecContext(ctx, setImageGPS,
		arg.GpsLat,
		arg.GpsLon,
		arg.GpsAttemptedAt,
		arg.ID,
	)
	return err
}
