// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: folders.sql

package sqlc

import (
	"context"
	"database/sql"
)

const countImagesInFolder = `-- name: CountImagesInFolder :one
SELECT COUNT(*) FROM images WHERE folder_id = ?
`

func (q *Queries) CountImagesInFolder(ctx context.Context, folderID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countImagesInFolder, folderID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createFolder = `-- name: CreateFolder :one
INSERT INTO folders (id, name, created_by) VALUES (?, ?, ?) RETURNING id, name, created_by, created_at, deleted_at
`

type CreateFolderParams struct {
	ID        string
	Name      string
	CreatedBy sql.NullString
}

func (q *Queries) CreateFolder(ctx context.Context, arg CreateFolderParams) (Folder, error) {
	row := q.db.QueryRowContext(ctx, createFolder, arg.ID, arg.Name, arg.CreatedBy)
	var i Folder
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getFolder = `-- name: GetFolder :one
SELECT id, name, created_by, created_at, deleted_at FROM folders WHERE id = ? AND deleted_at IS NULL
`

func (q *Queries) GetFolder(ctx context.Context, id string) (Folder, error) {
	row := q.db.QueryRowContext(ctx, getFolder, id)
	var i Folder
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getFolderIncludingDeleted = `-- name: GetFolderIncludingDeleted :one
SELECT id, name, created_by, created_at, deleted_at FROM folders WHERE id = ?
`

func (q *Queries) GetFolderIncludingDeleted(ctx context.Context, id string) (Folder, error) {
	row := q.db.QueryRowContext(ctx, getFolderIncludingDeleted, id)
	var i Folder
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const hardDeleteFolder = `-- name: HardDeleteFolder :exec
DELETE FROM folders WHERE id = ? AND deleted_at IS NOT NULL
`

func (q *Queries) HardDeleteFolder(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, hardDeleteFolder, id)
	return err
}

const listFolders = `-- name: ListFolders :many
SELECT f.id, f.name, f.created_at,
       (SELECT COUNT(*) FROM images i WHERE i.folder_id = f.id) AS image_count
FROM folders f
WHERE f.deleted_at IS NULL
ORDER BY f.created_at DESC, f.id
`

type ListFoldersRow struct {
	ID         string
	Name       string
	CreatedAt  string
	ImageCount int64
}

func (q *Queries) ListFolders(ctx context.Context) ([]ListFoldersRow, error) {
	rows, err := q.db.QueryContext(ctx, listFolders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFoldersRow
	for rows.Next() {
		var i ListFoldersRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.ImageCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const renameFolder = `-- name: RenameFolder :exec
UPDATE folders SET name = ? WHERE id = ? AND deleted_at IS NULL
`

type RenameFolderParams struct {
	Name string
	ID   string
}

func (q *Queries) RenameFolder(ctx context.Context, arg RenameFolderParams) error {
	_, err := q.db.ExecContext(ctx, renameFolder, arg.Name, arg.ID)
	return err
}

const softDeleteFolder = `-- name: SoftDeleteFolder :execrows
UPDATE folders SET deleted_at = ? WHERE id = ? AND deleted_at IS NULL
`

type SoftDeleteFolderParams struct {
	DeletedAt sql.NullString
	ID        string
}

func (q *Queries) SoftDeleteFolder(ctx context.Context, arg SoftDeleteFolderParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, softDeleteFolder, arg.DeletedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
