// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: images.sql

package sqlc

import (
	"context"
	"database/sql"
	"strings"
)

const getImage = `-- name: GetImage :one
SELECT i.seq, i.id, i.folder_id, i.original_filename, i.mime_type, i.size_bytes, i.width, i.height, i.sha256, i.uploader_nickname, i.rating, i.thumbnail_ready, i.preview_ready, i.created_at, i.device_key, i.exif_time, i.qr_scanned, i.is_calibration, i.calib_ref_time, i.time_offset_seconds, i.phash FROM images i
JOIN folders f ON f.id = i.folder_id
WHERE i.id = ? AND f.deleted_at IS NULL
`

func (q *Queries) GetImage(ctx context.Context, id string) (Image, error) {
	row := q.db.QueryRowContext(ctx, getImage, id)
	var i Image
	err := row.Scan(
		&i.Seq,
		&i.ID,
		&i.FolderID,
		&i.OriginalFilename,
		&i.MimeType,
		&i.SizeBytes,
		&i.Width,
		&i.Height,
		&i.Sha256,
		&i.UploaderNickname,
		&i.Rating,
		&i.ThumbnailReady,
		&i.PreviewReady,
		&i.CreatedAt,
		&i.DeviceKey,
		&i.ExifTime,
		&i.QrScanned,
		&i.IsCalibration,
		&i.CalibRefTime,
		&i.TimeOffsetSeconds,
		&i.Phash,
	)
	return i, err
}

const getImageBySha256InFolder = `-- name: GetImageBySha256InFolder :one
SELECT seq, id, folder_id, original_filename, mime_type, size_bytes, width, height, sha256, uploader_nickname, rating, thumbnail_ready, preview_ready, created_at, device_key, exif_time, qr_scanned, is_calibration, calib_ref_time, time_offset_seconds, phash FROM images WHERE folder_id = ? AND sha256 = ?
`

type GetImageBySha256InFolderParams struct {
	FolderID string
	Sha256   string
}

func (q *Queries) GetImageBySha256InFolder(ctx context.Context, arg GetImageBySha256InFolderParams) (Image, error) {
	row := q.db.QueryRowContext(ctx, getImageBySha256InFolder, arg.FolderID, arg.Sha256)
	var i Image
	err := row.Scan(
		&i.Seq,
		&i.ID,
		&i.FolderID,
		&i.OriginalFilename,
		&i.MimeType,
		&i.SizeBytes,
		&i.Width,
		&i.Height,
		&i.Sha256,
		&i.UploaderNickname,
		&i.Rating,
		&i.ThumbnailReady,
		&i.PreviewReady,
		&i.CreatedAt,
		&i.DeviceKey,
		&i.ExifTime,
		&i.QrScanned,
		&i.IsCalibration,
		&i.CalibRefTime,
		&i.TimeOffsetSeconds,
		&i.Phash,
	)
	return i, err
}

const getImageUnchecked = `-- name: GetImageUnchecked :one
SELECT seq, id, folder_id, original_filename, mime_type, size_bytes, width, height, sha256, uploader_nickname, rating, thumbnail_ready, preview_ready, created_at, device_key, exif_time, qr_scanned, is_calibration, calib_ref_time, time_offset_seconds, phash FROM images WHERE id = ?
`

func (q *Queries) GetImageUnchecked(ctx context.Context, id string) (Image, error) {
	row := q.db.QueryRowContext(ctx, getImageUnchecked, id)
	var i Image
	err := row.Scan(
		&i.Seq,
		&i.ID,
		&i.FolderID,
		&i.OriginalFilename,
		&i.MimeType,
		&i.SizeBytes,
		&i.Width,
		&i.Height,
		&i.Sha256,
		&i.UploaderNickname,
		&i.Rating,
		&i.ThumbnailReady,
		&i.PreviewReady,
		&i.CreatedAt,
		&i.DeviceKey,
		&i.ExifTime,
		&i.QrScanned,
		&i.IsCalibration,
		&i.CalibRefTime,
		&i.TimeOffsetSeconds,
		&i.Phash,
	)
	return i, err
}

const hardDeleteImage = `-- name: HardDeleteImage :execrows
DELETE FROM images WHERE id = ?
`

func (q *Queries) HardDeleteImage(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, hardDeleteImage, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const insertImage = `-- name: InsertImage :one
INSERT INTO images (id, folder_id, original_filename, mime_type, size_bytes, width, height, sha256, uploader_nickname, device_key, exif_time)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING seq, id, folder_id, original_filename, mime_type, size_bytes, width, height, sha256, uploader_nickname, rating, thumbnail_ready, preview_ready, created_at, device_key, exif_time, qr_scanned, is_calibration, calib_ref_time, time_offset_seconds, phash
`

type InsertImageParams struct {
	ID               string
	FolderID         string
	OriginalFilename string
	MimeType         string
	SizeBytes        int64
	Width            int64
	Height           int64
	Sha256           string
	UploaderNickname string
	DeviceKey        sql.NullString
	ExifTime         sql.NullString
}

func (q *Queries) InsertImage(ctx context.Context, arg InsertImageParams) (Image, error) {
	row := q.db.QueryRowContext(ctx, insertImage,
		arg.ID,
		arg.FolderID,
		arg.OriginalFilename,
		arg.MimeType,
		arg.SizeBytes,
		arg.Width,
		arg.Height,
		arg.Sha256,
		arg.UploaderNickname,
		arg.DeviceKey,
		arg.ExifTime,
	)
	var i Image
	err := row.Scan(
		&i.Seq,
		&i.ID,
		&i.FolderID,
		&i.OriginalFilename,
		&i.MimeType,
		&i.SizeBytes,
		&i.Width,
		&i.Height,
		&i.Sha256,
		&i.UploaderNickname,
		&i.Rating,
		&i.ThumbnailReady,
		&i.PreviewReady,
		&i.CreatedAt,
		&i.DeviceKey,
		&i.ExifTime,
		&i.QrScanned,
		&i.IsCalibration,
		&i.CalibRefTime,
		&i.TimeOffsetSeconds,
		&i.Phash,
	)
	return i, err
}

const listAllImageHashesInFolder = `-- name: ListAllImageHashesInFolder :many
SELECT id, phash FROM images WHERE folder_id = ? AND phash IS NOT NULL
`

type ListAllImageHashesInFolderRow struct {
	ID    string
	Phash sql.NullInt64
}

func (q *Queries) ListAllImageHashesInFolder(ctx context.Context, folderID string) ([]ListAllImageHashesInFolderRow, error) {
	rows, err := q.db.QueryContext(ctx, listAllImageHashesInFolder, folderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllImageHashesInFolderRow
	for rows.Next() {
		var i ListAllImageHashesInFolderRow
		if err := rows.Scan(&i.ID, &i.Phash); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExportImages = `-- name: ListExportImages :many
SELECT i.seq, i.id, i.folder_id, i.original_filename, i.mime_type, i.size_bytes, i.width, i.height, i.sha256, i.uploader_nickname, i.rating, i.thumbnail_ready, i.preview_ready, i.created_at, i.device_key, i.exif_time, i.qr_scanned, i.is_calibration, i.calib_ref_time, i.time_offset_seconds, i.phash FROM export_images ei
JOIN images i ON i.id = ei.image_id
WHERE ei.export_id = ?
ORDER BY i.seq
`

func (q *Queries) ListExportImages(ctx context.Context, exportID string) ([]Image, error) {
	rows, err := q.db.QueryContext(ctx, listExportImages, exportID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Image
	for rows.Next() {
		var i Image
		if err := rows.Scan(
			&i.Seq,
			&i.ID,
			&i.FolderID,
			&i.OriginalFilename,
			&i.MimeType,
			&i.SizeBytes,
			&i.Width,
			&i.Height,
			&i.Sha256,
			&i.UploaderNickname,
			&i.Rating,
			&i.ThumbnailReady,
			&i.PreviewReady,
			&i.CreatedAt,
			&i.DeviceKey,
			&i.ExifTime,
			&i.QrScanned,
			&i.IsCalibration,
			&i.CalibRefTime,
			&i.TimeOffsetSeconds,
			&i.Phash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFolderDevices = `-- name: ListFolderDevices :many
SELECT device_key, uploader_nickname,
       COUNT(*) AS image_count,
       CAST(COALESCE(SUM(is_calibration), 0) AS INTEGER) AS calibration_count,
       COUNT(time_offset_seconds) AS corrected_count,
       CAST(COALESCE(MIN(time_offset_seconds), 0) AS INTEGER) AS min_offset,
       CAST(COALESCE(MAX(time_offset_seconds), 0) AS INTEGER) AS max_offset
FROM images
WHERE folder_id = ? AND device_key IS NOT NULL
GROUP BY device_key, uploader_nickname
ORDER BY uploader_nickname, device_key
`

type ListFolderDevicesRow struct {
	DeviceKey        sql.NullString
	UploaderNickname string
	ImageCount       int64
	CalibrationCount int64
	CorrectedCount   int64
	MinOffset        int64
	MaxOffset        int64
}

func (q *Queries) ListFolderDevices(ctx context.Context, folderID string) ([]ListFolderDevicesRow, error) {
	rows, err := q.db.QueryContext(ctx, listFolderDevices, folderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFolderDevicesRow
	for rows.Next() {
		var i ListFolderDevicesRow
		if err := rows.Scan(
			&i.DeviceKey,
			&i.UploaderNickname,
			&i.ImageCount,
			&i.CalibrationCount,
			&i.CorrectedCount,
			&i.MinOffset,
			&i.MaxOffset,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listImageIDsInFolder = `-- name: ListImageIDsInFolder :many
SELECT id FROM images WHERE folder_id = ? ORDER BY seq
`

func (q *Queries) ListImageIDsInFolder(ctx context.Context, folderID string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listImageIDsInFolder, folderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listImagesByIDs = `-- name: ListImagesByIDs :many
SELECT seq, id, folder_id, original_filename, mime_type, size_bytes, width, height, sha256, uploader_nickname, rating, thumbnail_ready, preview_ready, created_at, device_key, exif_time, qr_scanned, is_calibration, calib_ref_time, time_offset_seconds, phash FROM images
WHERE folder_id = ? AND id IN (/*SLICE:image_ids*/?)
ORDER BY seq
`

type ListImagesByIDsParams struct {
	FolderID string
	ImageIds []string
}

func (q *Queries) ListImagesByIDs(ctx context.Context, arg ListImagesByIDsParams) ([]Image, error) {
	query := listImagesByIDs
	var queryParams []interface{}
	queryParams = append(queryParams, arg.FolderID)
	if len(arg.ImageIds) > 0 {
		for _, v := range arg.ImageIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:image_ids*/?", strings.Repeat(",?", len(arg.ImageIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:image_ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Image
	for rows.Next() {
		var i Image
		if err := rows.Scan(
			&i.Seq,
			&i.ID,
			&i.FolderID,
			&i.OriginalFilename,
			&i.MimeType,
			&i.SizeBytes,
			&i.Width,
			&i.Height,
			&i.Sha256,
			&i.UploaderNickname,
			&i.Rating,
			&i.ThumbnailReady,
			&i.PreviewReady,
			&i.CreatedAt,
			&i.DeviceKey,
			&i.ExifTime,
			&i.QrScanned,
			&i.IsCalibration,
			&i.CalibRefTime,
			&i.TimeOffsetSeconds,
			&i.Phash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listImagesInFolder = `-- name: ListImagesInFolder :many
SELECT seq, id, folder_id, original_filename, mime_type, size_bytes, width, height, sha256, uploader_nickname, rating, thumbnail_ready, preview_ready, created_at, device_key, exif_time, qr_scanned, is_calibration, calib_ref_time, time_offset_seconds, phash FROM images
WHERE folder_id = ? AND seq < ?2
ORDER BY seq DESC
LIMIT ?3
`

type ListImagesInFolderParams struct {
	FolderID  string
	BeforeSeq int64
	PageSize  int64
}

func (q *Queries) ListImagesInFolder(ctx context.Context, arg ListImagesInFolderParams) ([]Image, error) {
	rows, err := q.db.QueryContext(ctx, listImagesInFolder, arg.FolderID, arg.BeforeSeq, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Image
	for rows.Next() {
		var i Image
		if err := rows.Scan(
			&i.Seq,
			&i.ID,
			&i.FolderID,
			&i.OriginalFilename,
			&i.MimeType,
			&i.SizeBytes,
			&i.Width,
			&i.Height,
			&i.Sha256,
			&i.UploaderNickname,
			&i.Rating,
			&i.ThumbnailReady,
			&i.PreviewReady,
			&i.CreatedAt,
			&i.DeviceKey,
			&i.ExifTime,
			&i.QrScanned,
			&i.IsCalibration,
			&i.CalibRefTime,
			&i.TimeOffsetSeconds,
			&i.Phash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listImagesMissingPHash = `-- name: ListImagesMissingPHash :many
SELECT id, folder_id FROM images WHERE phash IS NULL
`

type ListImagesMissingPHashRow struct {
	ID       string
	FolderID string
}

func (q *Queries) ListImagesMissingPHash(ctx context.Context) ([]ListImagesMissingPHashRow, error) {
	rows, err := q.db.QueryContext(ctx, listImagesMissingPHash)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListImagesMissingPHashRow
	for rows.Next() {
		var i ListImagesMissingPHashRow
		if err := rows.Scan(&i.ID, &i.FolderID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markImageScanned = `-- name: MarkImageScanned :exec
UPDATE images SET qr_scanned = 1 WHERE id = ?
`

func (q *Queries) MarkImageScanned(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, markImageScanned, id)
	return err
}

const markPreviewReady = `-- name: MarkPreviewReady :exec
UPDATE images SET preview_ready = 1 WHERE id = ?
`

func (q *Queries) MarkPreviewReady(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, markPreviewReady, id)
	return err
}

const markThumbnailReady = `-- name: MarkThumbnailReady :exec
UPDATE images SET thumbnail_ready = 1 WHERE id = ?
`

func (q *Queries) MarkThumbnailReady(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, markThumbnailReady, id)
	return err
}

const recomputeDeviceOffsets = `-- name: RecomputeDeviceOffsets :exec
UPDATE images SET time_offset_seconds = (
    SELECT CAST(strftime('%s', c.calib_ref_time) AS INTEGER) - CAST(strftime('%s', c.exif_time) AS INTEGER)
    FROM images c
    WHERE c.folder_id = images.folder_id AND c.device_key = images.device_key
      AND c.is_calibration = 1 AND c.exif_time IS NOT NULL AND c.calib_ref_time IS NOT NULL
    ORDER BY ABS(CAST(strftime('%s', c.exif_time) AS INTEGER) - CAST(strftime('%s', images.exif_time) AS INTEGER)), c.seq
    LIMIT 1)
WHERE images.folder_id = ?1 AND images.device_key = ?2 AND images.exif_time IS NOT NULL
`

type RecomputeDeviceOffsetsParams struct {
	FolderID  string
	DeviceKey sql.NullString
}

// Recomputes the clock offset of every image of one device in a folder: each
// image uses the calibration shot nearest to it in (uncorrected) EXIF time.
// Images without any calibration for their device end up with NULL.
func (q *Queries) RecomputeDeviceOffsets(ctx context.Context, arg RecomputeDeviceOffsetsParams) error {
	_, err := q.db.ExecContext(ctx, recomputeDeviceOffsets, arg.FolderID, arg.DeviceKey)
	return err
}

const setImageCalibration = `-- name: SetImageCalibration :exec
UPDATE images SET is_calibration = 1, calib_ref_time = ? WHERE id = ?
`

type SetImageCalibrationParams struct {
	CalibRefTime sql.NullString
	ID           string
}

func (q *Queries) SetImageCalibration(ctx context.Context, arg SetImageCalibrationParams) error {
	_, err := q.db.ExecContext(ctx, setImageCalibration, arg.CalibRefTime, arg.ID)
	return err
}

const setImagePHash = `-- name: SetImagePHash :exec
UPDATE images SET phash = ? WHERE id = ?
`

type SetImagePHashParams struct {
	Phash sql.NullInt64
	ID    string
}

func (q *Queries) SetImagePHash(ctx context.Context, arg SetImagePHashParams) error {
	_, err := q.db.ExecContext(ctx, setImagePHash, arg.Phash, arg.ID)
	return err
}

const setImageRating = `-- name: SetImageRating :execrows
UPDATE images SET rating = ? WHERE id = ?
`

type SetImageRatingParams struct {
	Rating sql.NullInt64
	ID     string
}

func (q *Queries) SetImageRating(ctx context.Context, arg SetImageRatingParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setImageRating, arg.Rating, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
