// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: images.sql

package sqlc

import (
	"context"
	"database/sql"
	"strings"
)

const getImage = `-- name: GetImage :one
SELECT i.seq, i.id, i.folder_id, i.original_filename, i.mime_type, i.size_bytes, i.width, i.height, i.sha256, i.uploader_nickname, i.rating, i.thumbnail_ready, i.preview_ready, i.created_at FROM images i
JOIN folders f ON f.id = i.folder_id
WHERE i.id = ? AND f.deleted_at IS NULL
`

func (q *Queries) GetImage(ctx context.Context, id string) (Image, error) {
	row := q.db.QueryRowContext(ctx, getImage, id)
	var i Image
	err := row.Scan(
		&i.Seq,
		&i.ID,
		&i.FolderID,
		&i.OriginalFilename,
		&i.MimeType,
		&i.SizeBytes,
		&i.Width,
		&i.Height,
		&i.Sha256,
		&i.UploaderNickname,
		&i.Rating,
		&i.ThumbnailReady,
		&i.PreviewReady,
		&i.CreatedAt,
	)
	return i, err
}

const getImageUnchecked = `-- name: GetImageUnchecked :one
SELECT seq, id, folder_id, original_filename, mime_type, size_bytes, width, height, sha256, uploader_nickname, rating, thumbnail_ready, preview_ready, created_at FROM images WHERE id = ?
`

func (q *Queries) GetImageUnchecked(ctx context.Context, id string) (Image, error) {
	row := q.db.QueryRowContext(ctx, getImageUnchecked, id)
	var i Image
	err := row.Scan(
		&i.Seq,
		&i.ID,
		&i.FolderID,
		&i.OriginalFilename,
		&i.MimeType,
		&i.SizeBytes,
		&i.Width,
		&i.Height,
		&i.Sha256,
		&i.UploaderNickname,
		&i.Rating,
		&i.ThumbnailReady,
		&i.PreviewReady,
		&i.CreatedAt,
	)
	return i, err
}

const insertImage = `-- name: InsertImage :one
INSERT INTO images (id, folder_id, original_filename, mime_type, size_bytes, width, height, sha256, uploader_nickname)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING seq, id, folder_id, original_filename, mime_type, size_bytes, width, height, sha256, uploader_nickname, rating, thumbnail_ready, preview_ready, created_at
`

type InsertImageParams struct {
	ID               string
	FolderID         string
	OriginalFilename string
	MimeType         string
	SizeBytes        int64
	Width            int64
	Height           int64
	Sha256           string
	UploaderNickname string
}

func (q *Queries) InsertImage(ctx context.Context, arg InsertImageParams) (Image, error) {
	row := q.db.QueryRowContext(ctx, insertImage,
		arg.ID,
		arg.FolderID,
		arg.OriginalFilename,
		arg.MimeType,
		arg.SizeBytes,
		arg.Width,
		arg.Height,
		arg.Sha256,
		arg.UploaderNickname,
	)
	var i Image
	err := row.Scan(
		&i.Seq,
		&i.ID,
		&i.FolderID,
		&i.OriginalFilename,
		&i.MimeType,
		&i.SizeBytes,
		&i.Width,
		&i.Height,
		&i.Sha256,
		&i.UploaderNickname,
		&i.Rating,
		&i.ThumbnailReady,
		&i.PreviewReady,
		&i.CreatedAt,
	)
	return i, err
}

const listExportImages = `-- name: ListExportImages :many
SELECT i.seq, i.id, i.folder_id, i.original_filename, i.mime_type, i.size_bytes, i.width, i.height, i.sha256, i.uploader_nickname, i.rating, i.thumbnail_ready, i.preview_ready, i.created_at FROM export_images ei
JOIN images i ON i.id = ei.image_id
WHERE ei.export_id = ?
ORDER BY i.seq
`

func (q *Queries) ListExportImages(ctx context.Context, exportID string) ([]Image, error) {
	rows, err := q.db.QueryContext(ctx, listExportImages, exportID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Image
	for rows.Next() {
		var i Image
		if err := rows.Scan(
			&i.Seq,
			&i.ID,
			&i.FolderID,
			&i.OriginalFilename,
			&i.MimeType,
			&i.SizeBytes,
			&i.Width,
			&i.Height,
			&i.Sha256,
			&i.UploaderNickname,
			&i.Rating,
			&i.ThumbnailReady,
			&i.PreviewReady,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listImageIDsInFolder = `-- name: ListImageIDsInFolder :many
SELECT id FROM images WHERE folder_id = ? ORDER BY seq
`

func (q *Queries) ListImageIDsInFolder(ctx context.Context, folderID string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listImageIDsInFolder, folderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listImagesByIDs = `-- name: ListImagesByIDs :many
SELECT seq, id, folder_id, original_filename, mime_type, size_bytes, width, height, sha256, uploader_nickname, rating, thumbnail_ready, preview_ready, created_at FROM images
WHERE folder_id = ? AND id IN (/*SLICE:image_ids*/?)
ORDER BY seq
`

type ListImagesByIDsParams struct {
	FolderID string
	ImageIds []string
}

func (q *Queries) ListImagesByIDs(ctx context.Context, arg ListImagesByIDsParams) ([]Image, error) {
	query := listImagesByIDs
	var queryParams []interface{}
	queryParams = append(queryParams, arg.FolderID)
	if len(arg.ImageIds) > 0 {
		for _, v := range arg.ImageIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:image_ids*/?", strings.Repeat(",?", len(arg.ImageIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:image_ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Image
	for rows.Next() {
		var i Image
		if err := rows.Scan(
			&i.Seq,
			&i.ID,
			&i.FolderID,
			&i.OriginalFilename,
			&i.MimeType,
			&i.SizeBytes,
			&i.Width,
			&i.Height,
			&i.Sha256,
			&i.UploaderNickname,
			&i.Rating,
			&i.ThumbnailReady,
			&i.PreviewReady,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listImagesInFolder = `-- name: ListImagesInFolder :many
SELECT seq, id, folder_id, original_filename, mime_type, size_bytes, width, height, sha256, uploader_nickname, rating, thumbnail_ready, preview_ready, created_at FROM images
WHERE folder_id = ? AND seq < ?2
ORDER BY seq DESC
LIMIT ?3
`

type ListImagesInFolderParams struct {
	FolderID  string
	BeforeSeq int64
	PageSize  int64
}

func (q *Queries) ListImagesInFolder(ctx context.Context, arg ListImagesInFolderParams) ([]Image, error) {
	rows, err := q.db.QueryContext(ctx, listImagesInFolder, arg.FolderID, arg.BeforeSeq, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Image
	for rows.Next() {
		var i Image
		if err := rows.Scan(
			&i.Seq,
			&i.ID,
			&i.FolderID,
			&i.OriginalFilename,
			&i.MimeType,
			&i.SizeBytes,
			&i.Width,
			&i.Height,
			&i.Sha256,
			&i.UploaderNickname,
			&i.Rating,
			&i.ThumbnailReady,
			&i.PreviewReady,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markPreviewReady = `-- name: MarkPreviewReady :exec
UPDATE images SET preview_ready = 1 WHERE id = ?
`

func (q *Queries) MarkPreviewReady(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, markPreviewReady, id)
	return err
}

const markThumbnailReady = `-- name: MarkThumbnailReady :exec
UPDATE images SET thumbnail_ready = 1 WHERE id = ?
`

func (q *Queries) MarkThumbnailReady(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, markThumbnailReady, id)
	return err
}

const setImageRating = `-- name: SetImageRating :execrows
UPDATE images SET rating = ? WHERE id = ?
`

type SetImageRatingParams struct {
	Rating sql.NullInt64
	ID     string
}

func (q *Queries) SetImageRating(ctx context.Context, arg SetImageRatingParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setImageRating, arg.Rating, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
