// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: jobs.sql

package sqlc

import (
	"context"
	"database/sql"
)

const claimJob = `-- name: ClaimJob :one
UPDATE jobs
SET status = 'running', attempts = attempts + 1, started_at = ?1
WHERE id = (
    SELECT j.id FROM jobs j
    WHERE j.status = 'pending' AND j.run_at <= ?1
    ORDER BY j.run_at, j.id
    LIMIT 1
)
RETURNING id, type, payload, status, attempts, run_at, created_at, started_at, finished_at, error
`

func (q *Queries) ClaimJob(ctx context.Context, now sql.NullString) (Job, error) {
	row := q.db.QueryRowContext(ctx, claimJob, now)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Payload,
		&i.Status,
		&i.Attempts,
		&i.RunAt,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Error,
	)
	return i, err
}

const completeJob = `-- name: CompleteJob :exec
UPDATE jobs SET status = 'done', finished_at = ?, error = NULL WHERE id = ?
`

type CompleteJobParams struct {
	FinishedAt sql.NullString
	ID         int64
}

func (q *Queries) CompleteJob(ctx context.Context, arg CompleteJobParams) error {
	_, err := q.db.ExecContext(ctx, completeJob, arg.FinishedAt, arg.ID)
	return err
}

const deleteOldJobs = `-- name: DeleteOldJobs :exec
DELETE FROM jobs WHERE status = 'done' AND finished_at < ?
`

func (q *Queries) DeleteOldJobs(ctx context.Context, finishedAt sql.NullString) error {
	_, err := q.db.ExecContext(ctx, deleteOldJobs, finishedAt)
	return err
}

const enqueueJob = `-- name: EnqueueJob :one
INSERT INTO jobs (type, payload, run_at) VALUES (?, ?, ?) RETURNING id
`

type EnqueueJobParams struct {
	Type    string
	Payload string
	RunAt   string
}

func (q *Queries) EnqueueJob(ctx context.Context, arg EnqueueJobParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, enqueueJob, arg.Type, arg.Payload, arg.RunAt)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const failJob = `-- name: FailJob :exec
UPDATE jobs SET status = 'failed', finished_at = ?, error = ? WHERE id = ?
`

type FailJobParams struct {
	FinishedAt sql.NullString
	Error      sql.NullString
	ID         int64
}

func (q *Queries) FailJob(ctx context.Context, arg FailJobParams) error {
	_, err := q.db.ExecContext(ctx, failJob, arg.FinishedAt, arg.Error, arg.ID)
	return err
}

const listFailedJobs = `-- name: ListFailedJobs :many
SELECT id, type, payload, status, attempts, run_at, created_at, started_at, finished_at, error FROM jobs WHERE status = 'failed' ORDER BY id DESC LIMIT 100
`

func (q *Queries) ListFailedJobs(ctx context.Context) ([]Job, error) {
	rows, err := q.db.QueryContext(ctx, listFailedJobs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Job
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Payload,
			&i.Status,
			&i.Attempts,
			&i.RunAt,
			&i.CreatedAt,
			&i.StartedAt,
			&i.FinishedAt,
			&i.Error,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const manualRetryJob = `-- name: ManualRetryJob :execrows
UPDATE jobs SET status = 'pending', attempts = 0, run_at = ?, finished_at = NULL WHERE id = ? AND status = 'failed'
`

type ManualRetryJobParams struct {
	RunAt string
	ID    int64
}

func (q *Queries) ManualRetryJob(ctx context.Context, arg ManualRetryJobParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, manualRetryJob, arg.RunAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const requeueStaleJobs = `-- name: RequeueStaleJobs :execrows
UPDATE jobs SET status = 'pending', started_at = NULL
WHERE status = 'running' AND started_at < ?
`

func (q *Queries) RequeueStaleJobs(ctx context.Context, startedAt sql.NullString) (int64, error) {
	result, err := q.db.ExecContext(ctx, requeueStaleJobs, startedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const rescheduleJobByPayload = `-- name: RescheduleJobByPayload :execrows
UPDATE jobs SET run_at = ?
WHERE type = ? AND status = 'pending' AND payload = ?
`

type RescheduleJobByPayloadParams struct {
	RunAt   string
	Type    string
	Payload string
}

func (q *Queries) RescheduleJobByPayload(ctx context.Context, arg RescheduleJobByPayloadParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, rescheduleJobByPayload, arg.RunAt, arg.Type, arg.Payload)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const retryJobLater = `-- name: RetryJobLater :exec
UPDATE jobs SET status = 'pending', run_at = ?, error = ?, started_at = NULL WHERE id = ?
`

type RetryJobLaterParams struct {
	RunAt string
	Error sql.NullString
	ID    int64
}

func (q *Queries) RetryJobLater(ctx context.Context, arg RetryJobLaterParams) error {
	_, err := q.db.ExecContext(ctx, retryJobLater, arg.RunAt, arg.Error, arg.ID)
	return err
}
