// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"database/sql"
)

type Export struct {
	ID        string
	FolderID  string
	UserID    sql.NullString
	Status    string
	FileKey   sql.NullString
	SizeBytes sql.NullInt64
	Error     sql.NullString
	CreatedAt string
	ExpiresAt string
}

type ExportImage struct {
	ExportID string
	ImageID  string
}

type Folder struct {
	ID        string
	Name      string
	CreatedBy sql.NullString
	CreatedAt string
	DeletedAt sql.NullString
}

type FolderStandardTag struct {
	FolderID string
	TagID    int64
}

type Image struct {
	Seq               int64
	ID                string
	FolderID          string
	OriginalFilename  string
	MimeType          string
	SizeBytes         int64
	Width             int64
	Height            int64
	Sha256            string
	UploaderNickname  string
	Rating            sql.NullInt64
	ThumbnailReady    int64
	PreviewReady      int64
	CreatedAt         string
	DeviceKey         sql.NullString
	ExifTime          sql.NullString
	QrScanned         int64
	IsCalibration     int64
	CalibRefTime      sql.NullString
	TimeOffsetSeconds sql.NullInt64
}

type ImageTag struct {
	ImageID string
	TagID   int64
}

type Job struct {
	ID         int64
	Type       string
	Payload    string
	Status     string
	Attempts   int64
	RunAt      string
	CreatedAt  string
	StartedAt  sql.NullString
	FinishedAt sql.NullString
	Error      sql.NullString
}

type Session struct {
	TokenHash string
	UserID    string
	CsrfToken string
	CreatedAt string
	ExpiresAt string
}

type Tag struct {
	ID   int64
	Name string
}

type UploadLink struct {
	FolderID  string
	Token     string
	ExpiresAt string
	CreatedAt string
}

type User struct {
	ID        string
	OidcSub   string
	Email     string
	Name      string
	CreatedAt string
}
