// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package sqlc

import (
	"context"
)

const createSession = `-- name: CreateSession :exec
INSERT INTO sessions (token_hash, user_id, csrf_token, expires_at)
VALUES (?, ?, ?, ?)
`

type CreateSessionParams struct {
	TokenHash string
	UserID    string
	CsrfToken string
	ExpiresAt string
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.ExecContext(ctx, createSession,
		arg.TokenHash,
		arg.UserID,
		arg.CsrfToken,
		arg.ExpiresAt,
	)
	return err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :exec
DELETE FROM sessions WHERE expires_at <= ?
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context, expiresAt string) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredSessions, expiresAt)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE token_hash = ?
`

func (q *Queries) DeleteSession(ctx context.Context, tokenHash string) error {
	_, err := q.db.ExecContext(ctx, deleteSession, tokenHash)
	return err
}

const extendSession = `-- name: ExtendSession :exec
UPDATE sessions SET expires_at = ? WHERE token_hash = ?
`

type ExtendSessionParams struct {
	ExpiresAt string
	TokenHash string
}

func (q *Queries) ExtendSession(ctx context.Context, arg ExtendSessionParams) error {
	_, err := q.db.ExecContext(ctx, extendSession, arg.ExpiresAt, arg.TokenHash)
	return err
}

const getSession = `-- name: GetSession :one
SELECT s.token_hash, s.csrf_token, s.expires_at,
       u.id AS user_id, u.email, u.name
FROM sessions s
JOIN users u ON u.id = s.user_id
WHERE s.token_hash = ? AND s.expires_at > ?2
`

type GetSessionParams struct {
	TokenHash string
	Now       string
}

type GetSessionRow struct {
	TokenHash string
	CsrfToken string
	ExpiresAt string
	UserID    string
	Email     string
	Name      string
}

func (q *Queries) GetSession(ctx context.Context, arg GetSessionParams) (GetSessionRow, error) {
	row := q.db.QueryRowContext(ctx, getSession, arg.TokenHash, arg.Now)
	var i GetSessionRow
	err := row.Scan(
		&i.TokenHash,
		&i.CsrfToken,
		&i.ExpiresAt,
		&i.UserID,
		&i.Email,
		&i.Name,
	)
	return i, err
}
