// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tags.sql

package sqlc

import (
	"context"
	"database/sql"
	"strings"
)

const addFolderStandardTag = `-- name: AddFolderStandardTag :exec
INSERT OR IGNORE INTO folder_standard_tags (folder_id, tag_id) VALUES (?, ?)
`

type AddFolderStandardTagParams struct {
	FolderID string
	TagID    int64
}

func (q *Queries) AddFolderStandardTag(ctx context.Context, arg AddFolderStandardTagParams) error {
	_, err := q.db.ExecContext(ctx, addFolderStandardTag, arg.FolderID, arg.TagID)
	return err
}

const addImageTag = `-- name: AddImageTag :exec
INSERT OR IGNORE INTO image_tags (image_id, tag_id) VALUES (?, ?)
`

type AddImageTagParams struct {
	ImageID string
	TagID   int64
}

func (q *Queries) AddImageTag(ctx context.Context, arg AddImageTagParams) error {
	_, err := q.db.ExecContext(ctx, addImageTag, arg.ImageID, arg.TagID)
	return err
}

const listFolderStandardTags = `-- name: ListFolderStandardTags :many
SELECT t.id, t.name FROM folder_standard_tags fst
JOIN tags t ON t.id = fst.tag_id
WHERE fst.folder_id = ?
ORDER BY t.name
`

func (q *Queries) ListFolderStandardTags(ctx context.Context, folderID string) ([]Tag, error) {
	rows, err := q.db.QueryContext(ctx, listFolderStandardTags, folderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tag
	for rows.Next() {
		var i Tag
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listImageTags = `-- name: ListImageTags :many
SELECT t.id, t.name FROM image_tags it
JOIN tags t ON t.id = it.tag_id
WHERE it.image_id = ?
ORDER BY t.name
`

func (q *Queries) ListImageTags(ctx context.Context, imageID string) ([]Tag, error) {
	rows, err := q.db.QueryContext(ctx, listImageTags, imageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tag
	for rows.Next() {
		var i Tag
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTagsForExport = `-- name: ListTagsForExport :many
SELECT it.image_id, t.name FROM export_images ei
JOIN image_tags it ON it.image_id = ei.image_id
JOIN tags t ON t.id = it.tag_id
WHERE ei.export_id = ?
ORDER BY it.image_id, t.name
`

type ListTagsForExportRow struct {
	ImageID string
	Name    string
}

func (q *Queries) ListTagsForExport(ctx context.Context, exportID string) ([]ListTagsForExportRow, error) {
	rows, err := q.db.QueryContext(ctx, listTagsForExport, exportID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTagsForExportRow
	for rows.Next() {
		var i ListTagsForExportRow
		if err := rows.Scan(&i.ImageID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTagsForImages = `-- name: ListTagsForImages :many
SELECT it.image_id, t.name FROM image_tags it
JOIN tags t ON t.id = it.tag_id
WHERE it.image_id IN (/*SLICE:image_ids*/?)
ORDER BY it.image_id, t.name
`

type ListTagsForImagesRow struct {
	ImageID string
	Name    string
}

func (q *Queries) ListTagsForImages(ctx context.Context, imageIds []string) ([]ListTagsForImagesRow, error) {
	query := listTagsForImages
	var queryParams []interface{}
	if len(imageIds) > 0 {
		for _, v := range imageIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:image_ids*/?", strings.Repeat(",?", len(imageIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:image_ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTagsForImagesRow
	for rows.Next() {
		var i ListTagsForImagesRow
		if err := rows.Scan(&i.ImageID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeFolderStandardTag = `-- name: RemoveFolderStandardTag :exec
DELETE FROM folder_standard_tags WHERE folder_id = ? AND tag_id = ?
`

type RemoveFolderStandardTagParams struct {
	FolderID string
	TagID    int64
}

func (q *Queries) RemoveFolderStandardTag(ctx context.Context, arg RemoveFolderStandardTagParams) error {
	_, err := q.db.ExecContext(ctx, removeFolderStandardTag, arg.FolderID, arg.TagID)
	return err
}

const removeImageTag = `-- name: RemoveImageTag :exec
DELETE FROM image_tags WHERE image_id = ? AND tag_id = ?
`

type RemoveImageTagParams struct {
	ImageID string
	TagID   int64
}

func (q *Queries) RemoveImageTag(ctx context.Context, arg RemoveImageTagParams) error {
	_, err := q.db.ExecContext(ctx, removeImageTag, arg.ImageID, arg.TagID)
	return err
}

const suggestTags = `-- name: SuggestTags :many
SELECT name FROM tags WHERE name LIKE ?1 || '%' ESCAPE '\' ORDER BY name LIMIT 20
`

func (q *Queries) SuggestTags(ctx context.Context, prefix sql.NullString) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, suggestTags, prefix)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertTag = `-- name: UpsertTag :one
INSERT INTO tags (name) VALUES (?)
ON CONFLICT(name) DO UPDATE SET name = tags.name
RETURNING id, name
`

func (q *Queries) UpsertTag(ctx context.Context, name string) (Tag, error) {
	row := q.db.QueryRowContext(ctx, upsertTag, name)
	var i Tag
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}
