// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: upload_links.sql

package sqlc

import (
	"context"
)

const deleteUploadLink = `-- name: DeleteUploadLink :exec
DELETE FROM upload_links WHERE folder_id = ?
`

func (q *Queries) DeleteUploadLink(ctx context.Context, folderID string) error {
	_, err := q.db.ExecContext(ctx, deleteUploadLink, folderID)
	return err
}

const extendUploadLink = `-- name: ExtendUploadLink :execrows
UPDATE upload_links SET expires_at = ? WHERE folder_id = ?
`

type ExtendUploadLinkParams struct {
	ExpiresAt string
	FolderID  string
}

func (q *Queries) ExtendUploadLink(ctx context.Context, arg ExtendUploadLinkParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, extendUploadLink, arg.ExpiresAt, arg.FolderID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getUploadLinkByFolder = `-- name: GetUploadLinkByFolder :one
SELECT folder_id, token, expires_at, created_at FROM upload_links WHERE folder_id = ?
`

func (q *Queries) GetUploadLinkByFolder(ctx context.Context, folderID string) (UploadLink, error) {
	row := q.db.QueryRowContext(ctx, getUploadLinkByFolder, folderID)
	var i UploadLink
	err := row.Scan(
		&i.FolderID,
		&i.Token,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getUploadLinkByToken = `-- name: GetUploadLinkByToken :one
SELECT ul.folder_id, ul.token, ul.expires_at, f.name AS folder_name
FROM upload_links ul
JOIN folders f ON f.id = ul.folder_id
WHERE ul.token = ? AND f.deleted_at IS NULL
`

type GetUploadLinkByTokenRow struct {
	FolderID   string
	Token      string
	ExpiresAt  string
	FolderName string
}

func (q *Queries) GetUploadLinkByToken(ctx context.Context, token string) (GetUploadLinkByTokenRow, error) {
	row := q.db.QueryRowContext(ctx, getUploadLinkByToken, token)
	var i GetUploadLinkByTokenRow
	err := row.Scan(
		&i.FolderID,
		&i.Token,
		&i.ExpiresAt,
		&i.FolderName,
	)
	return i, err
}

const upsertUploadLink = `-- name: UpsertUploadLink :one
INSERT INTO upload_links (folder_id, token, expires_at)
VALUES (?, ?, ?)
ON CONFLICT(folder_id) DO UPDATE SET
    token = excluded.token,
    expires_at = excluded.expires_at,
    created_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
RETURNING folder_id, token, expires_at, created_at
`

type UpsertUploadLinkParams struct {
	FolderID  string
	Token     string
	ExpiresAt string
}

func (q *Queries) UpsertUploadLink(ctx context.Context, arg UpsertUploadLinkParams) (UploadLink, error) {
	row := q.db.QueryRowContext(ctx, upsertUploadLink, arg.FolderID, arg.Token, arg.ExpiresAt)
	var i UploadLink
	err := row.Scan(
		&i.FolderID,
		&i.Token,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}
