// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package sqlc

import (
	"context"
)

const getUser = `-- name: GetUser :one
SELECT id, oidc_sub, email, name, created_at FROM users WHERE id = ?
`

func (q *Queries) GetUser(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.OidcSub,
		&i.Email,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const upsertUser = `-- name: UpsertUser :one
INSERT INTO users (id, oidc_sub, email, name)
VALUES (?, ?, ?, ?)
ON CONFLICT(oidc_sub) DO UPDATE SET email = excluded.email, name = excluded.name
RETURNING id, oidc_sub, email, name, created_at
`

type UpsertUserParams struct {
	ID      string
	OidcSub string
	Email   string
	Name    string
}

func (q *Queries) UpsertUser(ctx context.Context, arg UpsertUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, upsertUser,
		arg.ID,
		arg.OidcSub,
		arg.Email,
		arg.Name,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.OidcSub,
		&i.Email,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}
